### ISSUE TITLE
Burger shop ladder interaction

### ISSUE THREAD

**Issue by NathanDGibbings** [CptVipezzz/RaccoonRummageGame#22]
The interaction for the top of the ladder on the burger shop is slightly too far out, interaction disappears if player stand right against the ledge/wall

**Comment by NathanDGibbings** [comment]
Seems to apply to more than just the mentioned ladder, also happens on some bottom interactions, need to do a check on all of them and adjust interaction colliders

**Comment by CptVipezzz** [comment]
all ladder bottoms expanded to solve issues
