### ISSUE TITLE
Character can become raised after 'climbing' certain objects.

### ISSUE THREAD

**Issue by NathanDGibbings** [CptVipezzz/RaccoonRummageGame#9]
Some objects, like trash bags for example, have a collider that can cause the player character to climb up and get stuck in an elevated state, which makes them unable to pick up any food, we should adjust these to make them impossible to climb in this manner.

**Comment by CptVipezzz** [comment]
All offending objects have been adjusted. Inaddition the players Y postion has also been frozen.
